spring.application.name=SpringBootforDevops
spring.mongodb.uri=${MongoDB_URI}
springdoc.api-docs.path=/My-apis
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
logging.file.name=/app/logs/application.log