name: spring boot ci
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MongoDB_URI: ${{ secrets.MONGODB_URI }}

    steps:
      - name: checkout source code
        uses: actions/checkout@v4

      - name: Setup java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          
      - name: Give Maven wrapper execute permission
        run: chmod +x ./mvnw

      - name: build with maven
        run: ./mvnw clean package

      - name: Build Docker image
        run: docker compose build

      - name: Start application
        run: docker compose up -d
        
      - name: Wait for application
        run: sleep 15

      - name: Running Container
        run: docker compose ps

      - name: Server logs
        run: docker compose logs

      - name: Test application
        run: curl -f http://localhost:8080/swagger-ui/index.html#/user-controller/getUsers

      - name: Wait for application
        run: sleep 15
  
      - name: Stop application
        if: always()
        run: docker compose down

